cmake_minimum_required(VERSION 3.16)
project(armor LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
find_package(OpenCV 4.13 REQUIRED COMPONENTS core imgproc videoio highgui calib3d dnn)
message(STATUS "This project uses OpenCV ${OpenCV_VERSION}: ${OpenCV_DIR}")
add_executable(armor main.cpp inference.cpp)
target_include_directories(armor PRIVATE ${OpenCV_INCLUDE_DIRS})
target_link_libraries(armor PRIVATE ${OpenCV_LIBS})
target_compile_definitions(armor PRIVATE PROJECT_DIRECTORY="${CMAKE_CURRENT_SOURCE_DIR}")
